version: "3.8"

services:
  db_test:
    image: postgres:15.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}_test

  backend_test:
    build:
      context: ./backend
    command: pytest
    env_file:
      - .env
    ports:
      - 8000:80
    depends_on:
      - db
