version: "3.8"

services:
  db:
    image: postgres:15.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - 8000:80
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - 80:80

volumes:
  db-data:
