version: "3.8"

services:
  db_test:
    image: postgres:15.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB_TEST?Variable not set}

  backend_test:
    build:
      context: ./backend
    command: bash -c "sleep 10; pytest"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db_test
    ports:
      - 8000:80
    depends_on:
      - db_test
