"""Add tags field to posts table

Revision ID: b28387a1a4a9
Revises: a4138e8bcb11
Create Date: 2023-10-13 15:38:28.313140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28387a1a4a9'
down_revision: Union[str, None] = 'a4138e8bcb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###
